-record(quote, {
        price, 
        change, 
        volume, 
        avg_daily_volume, 
        stock_exchange,
        market_cap, 
        book_value, 
        ebitda, 
        dividend_per_share, 
        dividend_yield, 
        earnings_per_share, 
        week_52_high, 
        week_52_low, 
        day_50_moving_avg,
        day_200_moving_avg, 
        price_earnings_ratio, 
        price_earnings_growth_ratio,
        price_sales_ratio, 
        price_book_ratio, 
        short_ratio}).

